version: "3.8"

services:
  mongodbpicme:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
    networks: #here
      - my-network

  picme-server:
    depends_on:
      - mongodbpicme
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    expose:
      - $NODE_LOCAL_PORT
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    networks: #here
      - my-network
    stdin_open: true
    tty: true

  picme-client:
    depends_on:
      - picme-server
    build:
      context: ./client
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"

networks: #here
  my-network:
    driver: bridge

volumes:
  db:
